### ISSUE TITLE
Propuesta para el diseño

### ISSUE THREAD

**Issue by JMEspiz** [ftliutval/ftliutval.github.io#16]
![1](https://cloud.githubusercontent.com/assets/9118537/9566505/8d5595d0-4ed1-11e5-9ff6-c91247f282dc.png)
![2](https://cloud.githubusercontent.com/assets/9118537/9566506/8d5bcde2-4ed1-11e5-8a5c-72bf9009a0e4.png)
![3](https://cloud.githubusercontent.com/assets/9118537/9566507/8d604b92-4ed1-11e5-87dd-875c234d61a8.png)

Esta es mi priopuesta para el diseño del home, en la parte superior no se ve la imagen de banner, de gustarles esta propuesta no se si estarian dispuesto a cambiar el fonde del banner por un color solido y colocarlo en la tarjeta principal, o reducirle un poco el alto.

Faltarian mas detalles como:

    Que funcionen las opciones de la tarjeta.
    Anexar nuevos elementos.
    Cambiar imagen de la Tarjeta por una oficial.
    Hacer el Modal con el FAQ.
    Entre otras que consideren y que este pasando por alto.

Saludos.

**Comment by fernandoparada18** [comment]
.
