### ISSUE TITLE
Definir Texto - Sección Inicio

### ISSUE THREAD

**Issue by Villanuevand** [ftliutval/ftliutval.github.io#2]
Se debe definir un texto para la sección Inicio del portal, y remover el texto de prueba que existe actualmente.

**Comment by JMEspiz** [comment]
Revisando las secciones podriamos plantenar que en esta seccion se debe informar al usuario todo lo relacionado con la estructuracion del evento (Dejando la vision, mision y deficnion del FTL a su seccion correspondiente):

- **Fechas y duracion** del mismo (*por dia*).
-  Direccion bien explicada del lugar (si se puede agregar un pequeño widget con Google Maps)
- Una imagen que invite a descubrir que es la FTL y cuales ponencias estan planificadas.

Tratar el home como una *landing pages* describiendo el evento de forma sutil pero concisa. Y no se opinan de una pequeña seccion de FAQ *(En un acordion dentro de un modal)* para por lo menos abordar temas como: 

- ¿Debo estudiar en el IUTVAL para poder asistir?
- ¿Si deseo algun certificado?
- ¿Puedo asistir parcialmente al evento y optar por el certificado?
- ¿Requisitos para asistir? (Explicar el proceso de registro tanto de participantes como de ponencias y dejando la seccion registro solo para el form de registro, si se manejara un limite de participantes y ponencias,como se hara la validacion asistencia dentro del evento)

Cosas asi. Que opinan?

**Comment by Villanuevand** [comment]
Me parece una muy buena idea, hay que desarrollar mejor la idea...

**Comment by JMEspiz** [comment]
Hice una prueba de como se veria con unas tarjetas al estilo MD, faltaria definir un color mas adecuado y modificar la distribucion del contenido para que se vea mejor, en caso de que esten de acuerdo en aplicar este estilo.
